---
- name: Ensure build dependencies
  ansible.builtin.apt:
    pkg:
      - gnupg
      - software-properties-common
      - wget
  tags:
    - twitchandtear

- name: Add the Apt signing key
  ansible.builtin.apt_key:
    url: http://debian.drdteam.org/drdteam.gpg
    state: present
  tags:
    - twitchandtear

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb http://debian.drdteam.org/ stable multiverse
    state: present
  tags:
    - twitchandtear

- name: Add the Zandronum package
  ansible.builtin.apt:
    pkg:
      - zandronum-client
  tags:
    - twitchandtear

- name: Check for linker config
  ansible.builtin.raw: test -e /etc/ld.so.conf.d/zandronum.conf
  changed_when: false
  failed_when: false
  register: check_zandronum_linker
  tags:
    - twitchandtear

- name: Update the linker to look for the included libraries
  ansible.builtin.shell: |
    echo '/usr/games/zandronum' > /etc/ld.so.conf.d/zandronum.conf
    ldconfig
  when: check_zandronum_linker.rc != 0
  changed_when: check_zandronum_linker.rc == 0
  tags:
    - twitchandtear

- name: Create zandronum user
  ansible.builtin.user:
    name: zandronum
    shell: /bin/bash
  tags:
    - twitchandtear

- name: Ensure config directory exists
  ansible.builtin.file:
    path: /home/zandronum/.config/zandronum
    state: directory
    owner: zandronum
    group: zandronum
    mode: '0755'
  tags:
    - twitchandtear

- name: Copy default configuration
  ansible.builtin.copy:
    src: ./
    dest: /home/zandronum/.config/zandronum/
    owner: zandronum
    group: zandronum
    mode: '0644'
  tags:
    - twitchandtear

- name: Add server scripts
  ansible.builtin.import_tasks: scripts.yml
  tags:
    - twitchandtear
